### ISSUE TITLE
[Bug] Channels not showing up

### ISSUE THREAD

**Issue by Zachary-Rude** [LauraWebdev/mgg-web#54] opened 2022-08-08 18:56 UTC
When I try to go to the Channel Overview page or add channels to my games, no channel names are showing up.

I'm very confused about this :/

**Comment by LauraWebdev** [comment] 2022-08-09 11:53
This is a duplicate of #38 in the server repo and a server issue.

**Closed as not planned** 2022-08-09 11:53 UTC
